---
title: "Gravity-fed Bioreactor Column Study"
author: "Katie L. Duggan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Files needed:

- "GFBR_icp_ic_results.csv"

## Load packages & set directory
```{r, include=FALSE}
#install.packages("tidyverse")
library(tidyverse)
library(ggpubr)
#install.packages("psych")
library(psych)
```

## Load data
```{r}
icp_ic_results <- read_csv("C:/github/WBR-microbiome/data/GFBR_icp_ic_results.csv") %>% 
  unite(datetime, c(date, time), sep = " ", remove = FALSE) #combine date and time
```

## Includes both replicates
```{r}
## Subset the data
control_run <- icp_ic_results %>% 
  filter(!replicate == "STOCK") %>%
  filter(!treatment == "P") %>% 
  filter(!treatment == "P+N")

P_run <- icp_ic_results %>% 
  filter(!replicate == "STOCK") %>%
  filter(!treatment == "Control")%>% 
  filter(!treatment == "P+N")

NP_run <- icp_ic_results %>% 
  filter(!replicate == "STOCK") %>%
  filter(!treatment == "Control")%>% 
  filter(!treatment == "P")

## Control run
breaks_C <- control_run %>% 
  pull(hours_after_start) %>% 
  unique()

timepoints_C <- ifelse(breaks_C > 120, breaks_C - 168, breaks_C)

control_run %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) +
  geom_line() +
  scale_x_continuous(breaks = breaks_C, labels = timepoints_C) +
  facet_wrap(~replicate, ncol = 1) +
  geom_vline(xintercept = c(120, 168, 288), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(title = "Phosphorus Trends in Gravity-fed Column Reactors - Control Run", color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Phosphorus Concentration (mg/L)") +
  theme(legend.position = "bottom",
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

## Phosphorus run
breaks_P <- P_run %>%
  pull(hours_after_start) %>% 
  unique()

timepoints_P <- ifelse(breaks_P > 456, breaks_P - 504, breaks_P - 336)

P_run %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) +
  geom_line() +
  scale_x_continuous(breaks = breaks_P, labels = timepoints_P) +
  facet_wrap(~replicate, ncol = 1) +
  geom_vline(xintercept = c(456, 504, 624), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(title = "Phosphorus Trends in Gravity-fed Column Reactors - Phosphorus Run", color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Phosphorus Concentration (mg/L)") +
  theme(legend.position = "bottom",
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

## Nitrate/Phosphorus run
breaks_N <- NP_run %>%
  pull(hours_after_start) %>% 
  unique()

timepoints_N <- ifelse(breaks_N > 792, breaks_N - 840, breaks_N - 672)

NP_run %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) +
  geom_line() +
  scale_x_continuous(breaks = breaks_N, labels = timepoints_N) +
  facet_wrap(~replicate, ncol = 1) +
  geom_vline(xintercept = c(792, 840, 960), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(title = "Phosphorus Trends in Gravity-fed Column Reactors - Nitrate/Phosphorus Run", color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Phosphorus Concentration (mg/L)") +
  theme(legend.position = "bottom",
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))
```

## Get the mean of the replicates
```{r}
## average the reps together
rep_mean_results <- icp_ic_results %>% 
  mutate(P_adj = ifelse(P < 0, 0, P)) %>% 
  group_by(names) %>% 
  mutate(mean_Al = mean(Al),
         mean_Ca = mean(Ca),
         mean_Fe = mean(Fe),
         mean_Mg = mean(Mg),
         mean_Mn = mean(Mn),
         mean_P = mean(P_adj),
         mean_S = mean(S),
         mean_Cl = mean(Cl),
         mean_NO2 = mean(NO2),
         mean_NO3 = mean(NO3),
         mean_PO4 = mean(PO4),
         mean_SO4 = mean(SO4)) %>% 
  ungroup() %>% 
  select(!c(sample_id, ICP_IC_batch, replicate, initial_p, initial_no3, Al, Ca, Fe, Mg, Mn, P, P_adj, S, Cl, NO2, NO3, PO4, SO4)) %>% 
  distinct(.keep_all = TRUE)

## pull out stock measurements
stock_samples <- rep_mean_results %>% 
  filter(reactor == "STOCK") %>% 
  select(names, cycle, treatment, datetime, mean_Al, mean_Ca, mean_Fe, mean_Mg, mean_Mn, mean_P, mean_S, mean_Cl, mean_NO2, mean_NO3, mean_PO4, mean_SO4)

stock_P <- stock_samples %>% 
  select(cycle, treatment, mean_P) %>% 
  rename("initial_P" = "mean_P")

## subset the average data and create an initial P column using the stock checks
mean_controlrun <- rep_mean_results %>%
  filter(!reactor == "STOCK") %>%
  filter(!treatment == "P") %>% 
  filter(!treatment == "P+N") %>% 
  mutate(initial_p = ifelse(cycle == 1, 0.0164, 0.0123)) %>% 
  mutate(initial_p = ifelse(reactor == "CNS", 0.0164, initial_p))

mean_Prun <- rep_mean_results %>% 
  filter(!reactor == "STOCK") %>%
  filter(!treatment == "Control")%>% 
  filter(!treatment == "P+N") %>% 
  mutate(initial_p = ifelse(cycle == 1, 0.250, 0.234)) %>% 
  mutate(initial_p = ifelse(reactor == "CNS", 0.250, initial_p))

mean_NPrun <- rep_mean_results %>% 
  filter(!reactor == "STOCK") %>%
  filter(!treatment == "Control")%>% 
  filter(!treatment == "P") %>% 
  mutate(initial_p = ifelse(cycle == 1, 0.188, 0.152)) %>% 
  mutate(initial_p = ifelse(reactor == "CNS", 0.188, initial_p))

## put the subsets back together into one dataset
tidyset <- rbind(mean_controlrun, mean_Prun, mean_NPrun) %>%
  rename(Al = mean_Al,
         Ca = mean_Ca,
         Fe = mean_Fe,
         Mg = mean_Mg,
         Mn = mean_Mn,
         P = mean_P,
         S = mean_S,
         Cl = mean_Cl,
         NO2 = mean_NO2,
         NO3 = mean_NO3,
         PO4 = mean_PO4,
         SO4 = mean_SO4) %>%
  mutate(decreaseP = ifelse(initial_p > P, TRUE, FALSE)) %>% 
  mutate(P_removal = initial_p - P) %>%
  mutate(pct_P_removal = ((initial_p - P)/initial_p) * 100)

breaks <- tidyset %>%
  pull(hours_after_start) %>% 
  unique()

timepoints <- c(timepoints_C, timepoints_P, timepoints_N)

tidyset %>% 
  ggplot(aes(x = hours_after_start, y = pct_P_removal, color = reactor)) + 
  geom_line() +
  scale_x_continuous(breaks = breaks, labels = timepoints) +
  #facet_wrap(~treatment, ncol = 1) +
  geom_vline(xintercept = c(120, 168, 288, 336, 456, 504, 624, 672, 792, 840, 960), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("% Phosphorus Removed") +
  theme(legend.position = "bottom",
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))
## This plot is a little weird because somehow all of the control samples had a higher P concentration than what it started with
## Were the woodchips still leaching P into the water from the field bioreactor?
```

## Cummulative plots
```{r}
# Full plot
tidyset %>%
  filter(!reactor == "STOCK") %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) + 
  geom_line() +
  scale_x_continuous(breaks = breaks, labels = timepoints) +
  #facet_wrap(~treatment, ncol = 1) +
  geom_vline(xintercept = c(120, 168, 288, 336, 456, 504, 624, 672, 792, 840, 960), color = "#BB0000", linetype = "dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Phosphorus Concentration (mg/L)") +
  theme(legend.position = "bottom",
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

# Control plot
control_plot <- tidyset %>%
  filter(!reactor == "STOCK") %>%
  filter(treatment == "Control") %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) + 
  geom_line() +
  scale_x_continuous(breaks = breaks_C, labels = timepoints_C) +
  #facet_wrap(~treatment, ncol = 1) +
  geom_vline(xintercept = c(120, 168, 288), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  ylim(c(0,0.3)) +
  xlab("Hours After Start") +
  ylab ("P Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(1,1,1,1), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

# P plot
P_plot <- tidyset %>%
  filter(!reactor == "STOCK") %>%
  filter(treatment == "P") %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) + 
  geom_line() +
  scale_x_continuous(breaks = breaks_P, labels = timepoints_P) +
  #facet_wrap(~treatment, ncol = 1) +
  geom_vline(xintercept = c(456, 504, 624), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  ylim(c(0,0.3)) +
  xlab("Hours After Start") +
  ylab ("P Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(1,1,1,1), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

# N/P plot
NP_plot <- tidyset %>%
  filter(!reactor == "STOCK") %>%
  filter(treatment == "P+N") %>%
  ggplot(aes(x = hours_after_start, y = P, color = reactor)) + 
  geom_line() +
  scale_x_continuous(breaks = breaks_N, labels = timepoints_N) +
  #facet_wrap(~treatment, ncol = 1) +
  geom_vline(xintercept = c(792, 840, 960), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  ylim(c(0,0.3)) +
  xlab("Hours After Start") +
  ylab ("P Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(1,1,1,1), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

ggarrange(control_plot, P_plot, NP_plot, ncol = 1, 
          labels = c("Control", "Phosphate", "Phosphate/Nitrate"), 
          hjust = -1, vjust = 1.5,
          common.legend = TRUE)
```

## All elements/compounds
```{r}
# Control plot
tidyset %>%
  filter(treatment == "Control") %>%
  pivot_longer(cols = c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4), 
               names_to = "chemical", values_to = "concentration") %>%
  ggplot(aes(x = hours_after_start, y = concentration, color = reactor)) + 
  geom_line() +
  facet_wrap(~chemical, ncol = 4, nrow = 3, scales = "free") +
  scale_x_continuous(breaks = breaks_C, labels = timepoints_C) +
  geom_vline(xintercept = c(120, 168, 288), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

# P run plot
tidyset %>%
  filter(treatment == "P") %>%
  pivot_longer(cols = c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4), 
               names_to = "chemical", values_to = "concentration") %>%
  ggplot(aes(x = hours_after_start, y = concentration, color = reactor)) + 
  geom_line() +
  facet_wrap(~chemical, ncol = 4, nrow = 3, scales = "free") +
  scale_x_continuous(breaks = breaks_P, labels = timepoints_P) +
  geom_vline(xintercept = c(456, 504, 624), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))

# NP run plot
tidyset %>%
  filter(treatment == "P+N") %>%
  pivot_longer(cols = c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4), 
               names_to = "chemical", values_to = "concentration") %>%
  ggplot(aes(x = hours_after_start, y = concentration, color = reactor)) + 
  geom_line() +
  facet_wrap(~chemical, ncol = 4, nrow = 3, scales = "free") +
  scale_x_continuous(breaks = breaks_N, labels = timepoints_N) +
  geom_vline(xintercept = c(792, 840, 960), color="#BB0000", linetype="dashed") +
  theme_classic() +
  labs(color = "Reactor:") +
  xlab("Hours After Start") +
  ylab ("Concentration (mg/L)") +
  theme(legend.position = "bottom",
        plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm"),
        panel.grid.major = element_line(color = "grey", linewidth = 0.25, linetype = 2),
        panel.grid.minor = element_line(color = "grey", linewidth = 0.25, linetype = 2))
```

## Correlation analysis
```{r}
C_CNS_corr <- tidyset %>% 
  filter(treatment == "Control") %>%
  filter(reactor == "CNS") %>% 
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal)) #%>% 
  #select(!c(mean_NO2, mean_PO4)) # columns are all 0, remove to avoid issues with correlation analysis

C_DRW_corr <- tidyset %>% 
  filter(treatment == "Control") %>%
  filter(reactor == "DRW") %>% 
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal)) #%>% 
  #select(!c(mean_NO2, mean_PO4)) # columns are all 0, remove to avoid issues with correlation analysis

P_CNS_corr <- tidyset %>% 
  filter(treatment == "P") %>% 
  filter(reactor == "CNS") %>% 
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal))

P_DRW_corr <- tidyset %>% 
  filter(treatment == "P") %>% 
  filter(reactor == "DRW") %>% 
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal))

N_CNS_corr <- tidyset %>% 
  filter(treatment == "P+N") %>% 
  filter(reactor == "CNS") %>%
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal))

N_DRW_corr <- tidyset %>% 
  filter(treatment == "P+N") %>% 
  filter(reactor == "DRW") %>%
  select(c(Al, Ca, Fe, Mg, Mn, P, S, Cl, NO2, NO3, PO4, SO4, initial_p, P_removal, pct_P_removal))

# Correlation plot for all elements/compounds (use spearman since it's nonparametric and does not have assumptions about distribution)
pairs.panels(C_CNS_corr, method = "spearman", stars = TRUE) + mtext("Control - CNS", side = 3, line = 4)
pairs.panels(C_DRW_corr, method = "spearman", stars = TRUE) + mtext("Control - DRW", side = 3, line = 4)
pairs.panels(P_CNS_corr, method = "spearman", stars = TRUE) + mtext("P treatment - CNS", side = 3, line = 4)
pairs.panels(P_DRW_corr, method = "spearman", stars = TRUE) + mtext("P treatment - DRW", side = 3, line = 4)
pairs.panels(N_CNS_corr, method = "spearman", stars = TRUE) + mtext("P+N treatment - CNS", side = 3, line = 4)
pairs.panels(N_DRW_corr, method = "spearman", stars = TRUE) + mtext("P+N treatment - DRW", side = 3, line = 4)

# Run correlation individually:
cor(P_correlation[,unlist(lapply(P_correlation, is.numeric))])

cor.test(P_correlation$mean_P, P_correlation$mean_Fe, method = "spearman")
### p value = 0.2127
```

## Modeling
```{r}
library("lme4")

model_treatment <- glm(formula = mean_P ~ treatment, data = tidyset)
summary(model_treatment)

model_reactor <- glm(formula = mean_P ~ reactor, data = tidyset)
summary(model_reactor)

model <- glm(formula = mean_P ~ reactor + treatment, data = tidyset)
summary(model)
```

