---
title: "MASH"
author: "Shapleigh"
date: "12/12/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory
```{r, include=FALSE}
setwd("C:/github/WBR-microbiome/")
```

Load required packages
```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
#install.packages("labdsv")
library(labdsv)
library(ggrepel)
```

This is output of the MASH run on the day this R file was made. See the MASH notebook in the O2-legacy folder. 

All reads
```{r}
dist.mat = read_tsv("C:/github/WBR-microbiome/data/data_from_JPS/sketch_all_comb_dist.tsv", col_names = c("sample_1", "sample_2", "dist", "p", "mash")) %>% 
  dplyr::select(sample_1, sample_2, dist) %>%
  tidyr::spread(sample_2, dist) %>% 
  dplyr::select(-sample_1)
    
pcoa = pco(dist.mat, k = 5)$points %>%
  data.frame %>%
  dplyr::rename("x" = X1, "y" = X2)
```

```{r}
df = data.frame(pcoa)

df$Sample = c("10U", "11M", "12U", "7M", "8U", "9M")

df$type = c("Unmilled", "Milled", "Unmilled", "Milled", "Unmilled", "Milled")

df %>% 
  ggplot(aes(x = x, y = y, color = type, label = Sample)) +
  geom_point(size = 2) +
  geom_label_repel(show.legend = FALSE, segment.colour = NA) +
  theme_bw() +
  labs(color = "Sample Preparation") +
  xlab("PCoA Axis 1") +
  ylab("PCoA Axis 2") +
  theme(axis.text = element_text(size = 12), axis.title = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 12), strip.text = element_text(size = 12))
```

