---
title: "MASH"
author: "Shapleigh"
date: "12/12/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load required packages
```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
#install.packages("labdsv")
library(labdsv)
library(ggrepel)
```

This is output of the MASH run on the day this R file was made. See the MASH notebook in the O2-legacy folder. 

All reads
```{r}
## Jim's work:
dist.mat = read_tsv("C:/github/WBR-microbiome/data/data_from_JPS/sketch_all_comb_dist.tsv", col_names = c("sample_1", "sample_2", "dist", "p", "mash")) %>% 
  dplyr::select(sample_1, sample_2, dist) %>%
  tidyr::spread(sample_2, dist) %>% 
  dplyr::select(-sample_1)
    
pcoa = pco(dist.mat, k = 5)$points %>%
  data.frame %>%
  dplyr::rename("x" = X1, "y" = X2)

df = data.frame(pcoa)

df$Sample = c("10U", "11M", "12U", "7M", "8U", "9M")

df$type = c("Unmilled", "Milled", "Unmilled", "Milled", "Unmilled", "Milled")

df %>% 
  ggplot(aes(x = x, y = y, color = type, label = Sample)) +
  geom_point(size = 2) +
  geom_label_repel(show.legend = FALSE, segment.colour = NA) +
  theme_bw() +
  labs(color = "Sample Preparation") +
  xlab("PCoA Axis 1") +
  ylab("PCoA Axis 2") +
  theme(axis.text = element_text(size = 12), axis.title = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 12), strip.text = element_text(size = 12))


## Katie's alternative (yields the same PCoA plot):
pcoa_mash <- cmdscale(dist.mat, eig = TRUE, add = TRUE)
pcoa_mash

positions_mash <- pcoa_mash$points #pulling out the point coordinates to plot them for each sample
positions_mash

colnames(positions_mash) <- c("pcoa1", "pcoa2") #renaming columns for ease of use in ggplot

percent_explained_mash <- 100* pcoa_mash$eig / sum(pcoa_mash$eig) #setup for axis labels

pretty_pe_mash <- format(round(percent_explained_mash[1:2], digits = 1), nsmall = 1, trim = TRUE) #setup for axis labels

labs_mash <- c(glue("PCo 1 ({pretty_pe_mash[1]}%)"), #setup for axis labels
          glue("PCo 2 ({pretty_pe_mash[2]}%)"))

## Main formatted plot for paper:
positions_mash %>% 
  as_tibble(rownames = "samples") %>% 
  mutate(treatment = c("Unmilled", "Milled", "Unmilled", "Milled", "Unmilled", "Milled")) %>% 
  mutate(label = c("U2", "M3", "U3", "M1", "U1", "M2")) %>% 
  ggplot(aes(x = pcoa1, y = pcoa2, color = treatment)) +
  geom_point(size = 3) +
  geom_label_repel(aes(label = label), show.legend = FALSE, segment.color = NA) +
  scale_color_manual(values = c("darkorange", "deepskyblue2")) +
  theme_classic() +
  labs(x = labs_mash[1], y = labs_mash[2], color = "Treatment")
```

```{r}
## PERMANOVA (following: https://www.youtube.com/watch?v=1ETBgbXl-BM)
dist_mat_clean <- dist.mat %>% 
  as.data.frame()

rownames(dist_mat_clean) <- c("U2", "M3", "U3", "M1", "U1", "M2")
colnames(dist_mat_clean) <- c("U2", "M3", "U3", "M1", "U1", "M2")

distance <- dist_mat_clean %>% 
  as_tibble() %>% 
  mutate("sample_id" = c("U2", "M3", "U3", "M1", "U1", "M2")) %>% 
  select(c("sample_id", "U2", "M3", "U3", "M1", "U1", "M2"))

metadata <- read.csv("C:/github/WBR-microbiome/data/pcoa_metadata.csv") %>% 
  #rename("sample_id" = "samples") %>% 
  as_tibble() %>% 
  mutate("sample_id" = c("M1", "U1", "M2", "U2", "M3", "U3")) %>% 
  select(!samples)

meta_distance <- inner_join(metadata, distance)

all_dist <- meta_distance %>% 
  select(all_of(.[["sample_id"]])) %>% 
  as.dist()

adonis2(all_dist ~ treatment + mass + yield + count, data = meta_distance) #returns p-value of 0.1 so the groups are not significantly different
```

