---
title: "Nonpareil WWTP"
author: "Jim Shapleigh"
date: '2023-01-26'
output: html_document
editor_options: 
  chunk_output_type: console
---

See info here https://nonpareil.readthedocs.io/en/latest/curves.html

```{r load library, include=FALSE}
library(tidyverse)
library(magrittr)
library(Nonpareil)
library(RColorBrewer)

display.brewer.all(colorblindFriendly = TRUE)
display.brewer.pal(n = 6, name = 'Set1')
display.brewer.pal(n = 6, name = 'Paired')
display.brewer.pal(n = 6, name = 'Dark2')
```

#To learn more about curve
```{r, eval=FALSE}
??Nonpareil.curve
```

To get curve and summary (with diversity value) for one file
```{r, eval=FALSE}
Nonpareil.curve('C:/github/WBR-microbiome/data/data_from_JPS/7G_QCS1.npo')

nps = Nonpareil.curve('C:/github/WBR-microbiome/data/data_from_JPS/7G_QCS1.npo')

summary(nps)
```

To get curve and summary (with diversity value) for set of files. Only way I could get this
to work. Need to see if there are any updated R files.
```{r}
npo_data.df = read_table("C:/github/WBR-microbiome/data/data_from_JPS/npo_files.txt", col_names=TRUE, col_types = "ccc")

info = as.vector(npo_data.df)

attach(info)

File <- c("C:/github/WBR-microbiome/data/data_from_JPS/7G_QCS1.npo", 
          "C:/github/WBR-microbiome/data/data_from_JPS/8W_QCS1.npo",
          "C:/github/WBR-microbiome/data/data_from_JPS/9G_QCS1.npo",
          "C:/github/WBR-microbiome/data/data_from_JPS/10W_QCS1.npo",
          "C:/github/WBR-microbiome/data/data_from_JPS/11G_QCS1.npo",
          "C:/github/WBR-microbiome/data/data_from_JPS/12W_QCS1.npo")

colors <- c("tomato3", "chocolate1", "gold", "green4", "dodgerblue", "darkorchid") #brewer.pal(n = 6, 'Paired')

labels <- c("M1 (22.07)", "M2 (21.96)", "M3 (21.87)", "U1 (22.14)", "U2 (22.01)" , "U3 (22.15)")

nps2 = Nonpareil.set(file = File, plot = TRUE, col = colors, labels = labels, plot.opts = list(plot.observed = TRUE, main = ""))

detach(info)

summary(nps2)
```
