---
title: "Carbohydrate-Active enZyme (CAZy) Presence in Milled vs Unmilled Woodchips"
author: "Katie L. Duggan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages & set directory
```{r, include=FALSE}
library(tidyverse)
library(ggpubr)
library(rstatix)
```

## Load data
```{r}
readcount <- read_csv("C:/Users/Katie/Documents/WBR-microbiome/data/Woodchip_DNAquality.csv") %>%
  rename(fn = filename)
```


## Stats

#### check assumptions
```{r}
## using: https://www.datanovia.com/en/lessons/t-test-in-r/

# summary stats
readcount %>%
  group_by(Treatment) %>%
  get_summary_stats(count, type = "mean_sd")

readcount %>%
  group_by(Treatment) %>%
  get_summary_stats(yield, type = "mean_sd")

readcount %>%
  group_by(Treatment) %>%
  get_summary_stats(mass, type = "mean_sd")

# summary boxplot
ggboxplot(readcount, x = "Treatment", y = "count", ylab = "Total Reads", xlab = "Treatment", add = "jitter")
ggboxplot(readcount, x = "Treatment", y = "yield", ylab = "DNA Concentration", xlab = "Treatment", add = "jitter")
ggboxplot(readcount, x = "Treatment", y = "mass", ylab = "Initial Sample Mass (g)", xlab = "Treatment", add = "jitter")

# identify outliers
readcount %>% group_by(Treatment) %>% identify_outliers(count) 
readcount %>% group_by(Treatment) %>% identify_outliers(yield) 
readcount %>% group_by(Treatment) %>% identify_outliers(mass) 
### The result of this function yields zero rows meaning that there were not outliers in our database.

# check normality
## The normality assumption can be checked by computing the Shapiro-Wilk test. 
## If the data is normally distributed, the p-value should be greater than 0.05.
readcount %>% group_by(Treatment) %>% shapiro_test(count)
readcount %>% group_by(Treatment) %>% shapiro_test(yield)
readcount %>% group_by(Treatment) %>% shapiro_test(mass)
### the two p-values are greater than the significance level 0.05 indicating that 
### the distribution of the data are not significantly different from the normal distribution. 
### In other words, we can assume the normality.

ggqqplot(readcount, x = "count", facet.by = "Treatment")
ggqqplot(readcount, x = "yield", facet.by = "Treatment")
ggqqplot(readcount, x = "mass", facet.by = "Treatment")
### All the points fall approximately along the reference line, for each group. So we can assume normality of the data.

# check equality of variances
## This can be done using the Levene’s test. If the variances of groups are equal, the p-value should be greater than 0.05.
readcount %>% levene_test(count ~ Treatment)
readcount %>% levene_test(yield ~ Treatment)
readcount %>% levene_test(mass ~ Treatment)
```

#### Welch's t-test for read count per million total reads:
```{r}
t_test(count ~ Treatment, data = readcount, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
### p-value = 0.228
### less than significance level of 0.05, so the means of the U and M groups are significantly different from each other.

t_test(yield ~ Treatment, data = readcount, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
### p-value = 0.682
### less than significance level of 0.05, so the means of the U and M groups are significantly different from each other.

t_test(mass ~ Treatment, data = readcount, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
### p-value = 0.176
### less than significance level of 0.05, so the means of the U and M groups are significantly different from each other.
```

